#!/usr/bin/env bash
# Configures ufw to forward port 8080/TCP to port 80/TCP on web-01

# Install ufw if not already installed
apt-get update -y
apt-get install ufw -y

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow specific TCP ports
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 8080/tcp

# Configure port forwarding (8080/TCP to 80/TCP)
echo "nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT" >> /etc/ufw/before.rules

# Enable ufw
ufw --force enable

# Output the modified ufw configuration file
cat /etc/ufw/before.rules